name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_docker_job:

    runs-on: ubuntu-latest
    name: a job to build docker

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag myresume:$(date +%s) -f Dockerfile .
